CREATE TABLE accounts
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_type VARCHAR(31),
    version      INTEGER                                  NOT NULL,
    creationTime TIMESTAMP WITHOUT TIME ZONE,
    updateTime   TIMESTAMP WITHOUT TIME ZONE,
    balance      DOUBLE PRECISION                         NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      INTEGER                                  NOT NULL,
    creationTime TIMESTAMP WITHOUT TIME ZONE,
    updateTime   TIMESTAMP WITHOUT TIME ZONE,
    firstName    VARCHAR(255),
    lastName     VARCHAR(255),
    email        VARCHAR(255),
    phone        VARCHAR(255),
    photoURL     VARCHAR(255),
    street       VARCHAR(255),
    city         VARCHAR(255),
    zipcode      VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE customers_accounts
(
    account_id  INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    CONSTRAINT pk_customers_accounts PRIMARY KEY (account_id, customer_id)
);

CREATE TABLE establishments
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      INTEGER                                  NOT NULL,
    creationTime TIMESTAMP WITHOUT TIME ZONE,
    updateTime   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255),
    CONSTRAINT pk_establishments PRIMARY KEY (id)
);

CREATE TABLE purchases
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          INTEGER                                  NOT NULL,
    creationTime     TIMESTAMP WITHOUT TIME ZONE,
    updateTime       TIMESTAMP WITHOUT TIME ZONE,
    establishment_id INTEGER,
    CONSTRAINT pk_purchases PRIMARY KEY (id)
);

CREATE TABLE recipients
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       INTEGER                                  NOT NULL,
    creationTime  TIMESTAMP WITHOUT TIME ZONE,
    updateTime    TIMESTAMP WITHOUT TIME ZONE,
    accountNumber INTEGER,
    name          VARCHAR(255),
    description   VARCHAR(255),
    customer_id   INTEGER,
    CONSTRAINT pk_recipients PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version         INTEGER                                  NOT NULL,
    creationTime    TIMESTAMP WITHOUT TIME ZONE,
    updateTime      TIMESTAMP WITHOUT TIME ZONE,
    amount          DOUBLE PRECISION,
    account_id      INTEGER,
    purchase_id     INTEGER,
    recipient_id    INTEGER,
    transactionType VARCHAR(255),
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE purchases
    ADD CONSTRAINT FK_PURCHASES_ON_ESTABLISHMENT FOREIGN KEY (establishment_id) REFERENCES establishments (id);

ALTER TABLE recipients
    ADD CONSTRAINT FK_RECIPIENTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_PURCHASE FOREIGN KEY (purchase_id) REFERENCES purchases (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES recipients (id);

ALTER TABLE customers_accounts
    ADD CONSTRAINT fk_cusacc_on_account FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE customers_accounts
    ADD CONSTRAINT fk_cusacc_on_customer FOREIGN KEY (customer_id) REFERENCES customers (id);